apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: clayton-deploy
  name: clayton-deploy
spec:
  replicas: 5
  selector:
    matchLabels:
      app: clayton-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: clayton-deploy
    spec:
      containers:
      - image: nginx
        name: nginx
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
          requests:
            memory: "128Mi"
            cpu: "50m"          
status: {}
